---
cephadm_ceph_release: pacific
cephadm_skip_prechecks: False
# FSID
cephadm_fsid: ""
# Recreate cluster
cephadm_recreate: False
# Packages
cephadm_custom_repos: False
cephadm_package_update: False
# Image
cephadm_image: ""
# Registry
cephadm_registry_url: ""
cephadm_registry_username: ""
cephadm_registry_password: ""
# Bootstrap settings
cephadm_bootstrap_host: "{{ groups['mons'][0] }}"
cephadm_enable_dashboard: False
cephadm_enable_firewalld: False
cephadm_enable_monitoring: False
cephadm_install_ceph_cli: False
cephadm_ssh_public_key: "/etc/ceph/cephadm.pub"
cephadm_ssh_private_key: "/etc/ceph/cephadm.id"
cephadm_ssh_user: "{{ ansible_facts.ansible_user if ansible_facts.ansible_user is defined else '' }}"
cephadm_bootstrap_additional_parameters: ""
cephadm_apt_repo_dist: "{{ ansible_facts.distribution_release }}"
# MONs and MGRs
cephadm_mon_count: "{{ groups.get('mons', []) | length }}"
cephadm_mgr_count: "{{ groups.get('mgrs', []) | length }}"
# Networking
cephadm_admin_interface: "{{ cephadm_public_interface }}"
cephadm_public_interface: ""
cephadm_cluster_interface: ""
cephadm_public_network: ""
cephadm_cluster_network: ""
# OSDs
cephadm_osd_devices: []
cephadm_osd_spec: []
# RADOSGW
cephadm_radosgw_services: []
